using Microsoft.EntityFrameworkCore;
using ExpenseTracker.Models;

namespace ExpenseTracker.Data
{
    /// <summary>
    /// Database context class for the Expense Tracker application.
    /// This class manages the database connection and entity configurations using Entity Framework Core.
    /// It serves as the bridge between the application and the SQLite database.
    /// </summary>
    public class AppDbContext : DbContext
    {
        /// <summary>
        /// Constructor that initializes the DbContext with the provided options.
        /// The options are configured in Program.cs and include the database connection string.
        /// </summary>
        /// <param name="options">Configuration options for the DbContext, including connection string</param>
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        /// <summary>
        /// DbSet representing the Expenses table in the database.
        /// Provides access to query and save instances of Expense entities.
        /// Used by the controller to perform CRUD operations on expense data.
        /// </summary>
        public DbSet<Expense> Expenses { get; set; }

        /// <summary>
        /// Configures the database model and relationships using the Fluent API.
        /// This method is called when the model for the context is being created.
        /// </summary>
        /// <param name="modelBuilder">The builder being used to construct the model for this context</param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Configure the primary key for the Expense entity
            // Explicitly defines Id as the primary key for the Expenses table
            modelBuilder.Entity<Expense>()
                .HasKey(e => e.Id);

            // Configure the Id property to be auto-generated by the database
            // This enables auto-increment functionality for the primary key
            modelBuilder.Entity<Expense>()
                .Property(e => e.Id)
                .ValueGeneratedOnAdd();

            // Configure the Amount property to use decimal precision
            // Sets precision to 18 digits total with 2 decimal places (e.g., 9999999999999999.99)
            // This ensures accurate storage of monetary values in the database
            modelBuilder.Entity<Expense>()
                .Property(e => e.Amount)
                .HasPrecision(18, 2);
        }
    }
}
