using System;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace ExpenseTracker.Models
{
    /// <summary>
    /// Represents an expense entry in the Expense Tracker application.
    /// </summary>
    public class Expense
    {
        /// <summary>
        /// Primary key for the Expense entity.
        /// Auto-generated by the database when a new expense is created.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Foreign key linking this expense to a user.
        /// Nullable so API requests without UserId do not fail.
        /// </summary>
        public int? UserId { get; set; }

        /// <summary>
        /// Navigation property to the user who owns this expense.
        /// Ignored during JSON serialization to prevent API POST errors.
        /// </summary>
        [JsonIgnore]
        public User? User { get; set; }

        /// <summary>
        /// Brief description of the expense.
        /// </summary>
        [Required(ErrorMessage = "Description is required")]
        [StringLength(100, ErrorMessage = "Description cannot be longer than 100 characters")]
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Monetary amount of the expense.
        /// </summary>
        [Required(ErrorMessage = "Amount is required")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        [DataType(DataType.Currency)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Category classification for the expense.
        /// </summary>
        [Required(ErrorMessage = "Category is required")]
        [StringLength(50, ErrorMessage = "Category cannot be longer than 50 characters")]
        public string Category { get; set; } = string.Empty;

        /// <summary>
        /// The date when the expense occurred.
        /// </summary>
        [Required(ErrorMessage = "Date is required")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        /// <summary>
        /// Optional notes about the expense.
        /// </summary>
        [StringLength(500, ErrorMessage = "Notes cannot be longer than 500 characters")]
        public string? Notes { get; set; }

        /// <summary>
        /// Timestamp when this expense was created.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.Now;
    }
}