using System;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace ExpenseTracker.Models
{

    /// Represents an expense entry in the Expense Tracker application.

    public class Expense
    {
      
        /// Primary key for the Expense entity.
        /// Auto-generated by the database when a new expense is created.
  
        public int Id { get; set; }

        /// Foreign key linking this expense to a user.
        /// Nullable so API requests without UserId do not fail.
 
        public int? UserId { get; set; }


        /// Navigation property to the user who owns this expense.
        /// Ignored during JSON serialization to prevent API POST errors.
   
        [JsonIgnore]
        public User? User { get; set; }

        /// Brief description of the expense.

        [Required(ErrorMessage = "Description is required")]
        [StringLength(100, ErrorMessage = "Description cannot be longer than 100 characters")]
        public string Description { get; set; } = string.Empty;

        /// Monetary amount of the expense.

        [Required(ErrorMessage = "Amount is required")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        [DataType(DataType.Currency)]
        public decimal Amount { get; set; }

        /// Category classification for the expense.
        [Required(ErrorMessage = "Category is required")]
        [StringLength(50, ErrorMessage = "Category cannot be longer than 50 characters")]
        public string Category { get; set; } = string.Empty;

        /// The date when the expense occurred.

        [Required(ErrorMessage = "Date is required")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        /// Optional notes about the expense.

        [StringLength(500, ErrorMessage = "Notes cannot be longer than 500 characters")]
        public string? Notes { get; set; }

        /// Timestamp when this expense was created.
     
        public DateTime CreatedAt { get; set; } = DateTime.Now;
    }
}