using System;
using System.ComponentModel.DataAnnotations;

namespace ExpenseTracker.Models
{
    /// <summary>
    /// Represents an expense entry in the Expense Tracker application.
    /// This model contains all the information related to a single expense transaction.
    /// </summary>
    public class Expense
    {
        /// <summary>
        /// Primary key for the Expense entity.
        /// Auto-generated by the database when a new expense is created.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Brief description of the expense (e.g., "Grocery Shopping", "Gas Station").
        /// Must be provided and cannot exceed 100 characters.
        /// </summary>
        [Required(ErrorMessage = "Description is required")]
        [StringLength(100, ErrorMessage = "Description cannot be longer than 100 characters")]
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// The monetary amount of the expense.
        /// Must be greater than 0 and is stored with currency formatting.
        /// </summary>
        [Required(ErrorMessage = "Amount is required")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        [DataType(DataType.Currency)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Category classification for the expense (e.g., Food, Transportation, Entertainment).
        /// Helps organize and filter expenses by type. Required field with max length of 50 characters.
        /// </summary>
        [Required(ErrorMessage = "Category is required")]
        [StringLength(50, ErrorMessage = "Category cannot be longer than 50 characters")]
        public string Category { get; set; } = string.Empty;

        /// <summary>
        /// The date when the expense occurred.
        /// Required field displayed as a date picker in the UI.
        /// </summary>
        [Required(ErrorMessage = "Date is required")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        /// <summary>
        /// Optional additional notes or details about the expense.
        /// Can contain up to 500 characters for extra context.
        /// </summary>
        [StringLength(500, ErrorMessage = "Notes cannot be longer than 500 characters")]
        public string? Notes { get; set; }

        /// <summary>
        /// Timestamp indicating when this expense record was created in the system.
        /// Automatically set to the current date and time when the object is instantiated.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.Now;
    }
}
